# Generated by Django 5.1.6 on 2025-03-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Portal_Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
