# Generated by Django 5.1.6 on 2025-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Portal_Game', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
